version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=spring'
      - 'POSTGRES_PASSWORD=spring'
      - 'POSTGRES_USER=spring'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - 'redis-data:/data'

volumes:
  postgres-data:
  redis-data:
