spring:
  liquibase:
    change-log: classpath:classpath:/db/master.xml
  devtools:
    livereload:
      port: 35730

rsa:
  public-key: classpath:certs/public-key.pem
  private-key: classpath:certs/private-key.pem

sendgrid:
  api-key: ${SENDGRID_API_KEY}
  sender-email: ${SENDGRID_SENDER_EMAIL}